[package]
name    = "LlamaEdge-Q"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow             = "1.0"
async-trait        = "0.1.82"
axum               = { version = "^0.8", features = ["tokio", "http2"] }
clap               = { version = "^4.5", features = ["cargo", "derive"] }
config             = { version = "0.15", features = ["toml"] }
endpoints          = "0.25.0"
reqwest            = { version = "^0.12", default-features = false, features = ["rustls-tls", "json", "stream"] }
serde              = { version = "1.0", features = ["derive"] }
serde_json         = "1.0"
thiserror          = "2.0"
tokio              = { version = "1.0", features = ["full"] }
tower              = { version = "^0.5", features = ["util"] }
tower-http         = { version = "^0.6", features = ["trace", "cors"] }
tracing            = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
