[server]
host = "127.0.0.1" # The host to listen on.
port = 3389        # The port to listen on.


# Section 1: RAG
#
# The following items are the configuration for the RAG service:
#
# - enable: Whether to enable RAG. When it is true, the `mcp.server.vector_search` is required to be enabled. The `mcp.server.keyword_search` should also be enabled if you want to use keyword search in the retrieval phase.
# - prompt: Custom rag prompt. Optional.
# - policy: Strategy for merging RAG context into chat messages. Possible values: "system-message", "last-user-message". Required if enable is true.
# - context_window: Maximum number of user messages used in the retrieval.
#
# Note that, if enable is true, then Section 2.1 must be enabled, and Section 2.2 is optional.

[rag]
enable         = false
policy         = "last-user-message"
prompt         = "# Context\n\nPlease answer the user question based on the following retrieved information:"
context_window = 1


# Section 1.1: Vector Search
#
# The following items are the vector search mcp server configurations:
#
# - name: The name of the mcp server.
# - transport: The transport protocol to use. Possible values: "sse", "stdio", "streamable-http". Note that ONLY "sse" is supported for now.
# - url: The URL of the mcp server.
# - enable: Whether to enable the mcp server.
#
# Note that, to use the configuration, comment out one of the following items and
# uncomment the corresponding item in the following sections.

[mcp.server.vector_search]
name      = "gaia-qdrant"
transport = "sse"
url       = "http://127.0.0.1:8003/sse"
enable    = false


# Section 1.2: Keyword Search
#
# The following items are the keyword search mcp server configurations:
#
# - name: The name of the mcp server.
# - transport: The transport protocol to use. Possible values: "sse", "stdio", "streamable-http". Note that ONLY "sse" is supported for now.
# - url: The URL of the mcp server.
# - enable: Whether to enable the mcp server.
#
# Note that, to use the configuration, comment out one of the following items and
# uncomment the corresponding item in the following sections

[mcp.server.keyword_search]
name      = "gaia-keyword-search"
transport = "sse"
url       = "http://127.0.0.1:8005/sse"
enable    = false

# [mcp.server.keyword_search]
# name      = "gaia-elastic-search"
# transport = "sse"
# url       = "http://127.0.0.1:8006/sse"
# enable    = false

# [mcp.server.keyword_search]
# name      = "gaia-tidb-search"
# transport = "sse"
# url       = "http://127.0.0.1:8007/sse"
# enable    = false
