[server]
host = "127.0.0.1" # The host to listen on.
port = 3389        # The port to listen on.


# RAG
#
# The following items are the configuration for the RAG service:
#
# - enable: Whether to enable RAG. When it is true, the `mcp.server.vector_search` is required to be enabled. The `mcp.server.keyword_search` should also be enabled if you want to use keyword search in the retrieval phase.
# - policy: Strategy for merging RAG context into chat messages. Possible values: "system-message", "last-user-message". Required if enable is true.
# - context_window: Maximum number of user messages used in the retrieval.

[rag]
enable         = false
policy         = "last-user-message"
context_window = 1


# Vector Search MCP Server
#
# The following items are the vector search mcp server configurations:
#
# - name: The name of the mcp server.
# - transport: The transport protocol to use. Possible values: "sse", "stream-http".
# - url: The URL of the mcp server.
# - enable: Whether to enable the mcp server.

[[mcp.server.tool]]
name      = "gaia-qdrant"
transport = "stream-http"
url       = "http://127.0.0.1:8003/mcp"
enable    = false


# Keyword Search MCP Servers
#
# The following items are the keyword search mcp server configurations:
#
# - name: The name of the mcp server.
# - transport: The transport protocol to use. Possible values: "sse", "stdio", "stream-http".
# - url: The URL of the mcp server.
# - enable: Whether to enable the mcp server.
#
# If you want to use keyword search in the retrieval phase, please enable one of the following
# three keyword search mcp servers.

[[mcp.server.tool]]
name      = "gaia-keyword-search"
transport = "stream-http"
url       = "http://127.0.0.1:8005/mcp"
enable    = false

[[mcp.server.tool]]
name      = "gaia-elastic-search"
transport = "stream-http"
url       = "http://127.0.0.1:8006/mcp"
enable    = false

[[mcp.server.tool]]
name      = "gaia-tidb-search"
transport = "stream-http"
url       = "http://127.0.0.1:8007/mcp"
enable    = false


# MCP Servers
#
# The following items are the configuration for the MCP tool servers:
#
# - name: The name of the MCP tool server.
# - transport: The transport protocol to use. Possible values: "sse", "stdio", "streamable-http". Note that ONLY "sse" is supported for now.
# - url: The URL of the MCP tool server.
# - enable: Whether to enable the MCP tool server.
#
# Note that, if any of the MCP tool servers are enabled, then please guarantee that the
# corresponding mcp server is started.

[[mcp.server.tool]]
name      = "gaia-calculator"
transport = "stream-http"
url       = "http://127.0.0.1:8001/mcp"
enable    = false

[[mcp.server.tool]]
name      = "gaia-weather"
transport = "stream-http"
url       = "http://127.0.0.1:8002/mcp"
enable    = false
