[server]
host = "0.0.0.0" # The host to listen on.
port = 8080      # The port to listen on.


# The following items are the configuration for the RAG service:
#
# rag.enable: Whether to enable RAG. When it is true, the `mcp.server.vector_search` is required to be enabled. The `mcp.server.keyword_search` should also be enabled if you want to use keyword search in the retrieval phase.
# rag.prompt: Custom rag prompt. Optional.
# rag.policy: Strategy for merging RAG context into chat messages. Possible values: "system-message", "last-user-message". Required if enable is true.
# rag.context_window: Maximum number of user messages used in the retrieval.

[rag]
enable         = false
policy         = "last-user-message"
prompt         = "# Context\n\nPlease answer the user question based on the following retrieved information:"
context_window = 1


# The following items are the configuration for the MCP tool servers:
#
# name: The name of the MCP tool server.
# transport: The transport protocol to use. Possible values: "sse", "stdio", "streamable-http". Note that ONLY "sse" is supported for now.
# url: The URL of the MCP tool server.
# enable: Whether to enable the MCP tool server.

[[mcp.server.tool]]
name      = "gaia-calculator"
transport = "sse"
url       = "http://127.0.0.1:8001/sse"
enable    = false

[[mcp.server.tool]]
name      = "gaia-weather"
transport = "sse"
url       = "http://127.0.0.1:8002/sse"
enable    = false

[mcp.server.vector_search]
name      = "gaia-qdrant"
transport = "sse"
url       = "http://127.0.0.1:8003/sse"
enable    = false

[mcp.server.keyword_search]
name      = "gaia-keyword-search"
transport = "sse"
url       = "http://127.0.0.1:8005/sse"
enable    = false

# [[mcp]]
# name      = "gaia-elastic-search"
# transport = "sse"
# url       = "http://127.0.0.1:8006/sse"
# enable    = false
